### ISSUE TITLE
Sass comments not being highlighted

### ISSUE THREAD

**Issue by nothingrandom** [Centril/sublime-monocyanide-colorscheme#1]
Comments in Sass in the format `// comment` aren't styled correctly. However, comments in the format `/* comment */` are formatted.

**Comment by Centril** [comment]
Thanks, I'll try to fix it today.

**Comment by Centril** [comment]
I am really sorry for replying so super late...
I checked with ScopeHunter now and unfortunately, there's no scope for the `//` style comment with SASS or SCSS so there's nothing I can do - the fault lies with sublime-text.

Maybe you can solve it by getting a better SASS language definition.
